#!/usr/bin/env bash
set -e

REPO_USER="Mahamutu"
REPO_NAME="AllumeriaEnhanced"
USER_AGENT="Mozilla/5.0 (X11; Linux x86_64) AllumeriaInstaller"

# Locate Game Directory
find_game_dir() {
  if [ -n "$ALLUMERIA_GAME_PATH" ] && [ -f "$ALLUMERIA_GAME_PATH/Allumeria.exe" ]; then
    echo "$ALLUMERIA_GAME_PATH"
    return
  fi

  # Check common Steam library paths for Allumeria.exe
  for path in \
    "$HOME/.local/share/Steam/steamapps/common/Allumeria" \
    "$HOME/.steam/steam/steamapps/common/Allumeria" \
    "$HOME/.steam/root/steamapps/common/Allumeria" \
    "/run/media/mmcblk0p1/steamapps/common/Allumeria" \
    "/media/$USER/*/steamapps/common/Allumeria" \
    "/mnt/*/steamapps/common/Allumeria"; do
    if [ -f "$path/Allumeria.exe" ]; then
      echo "$path"
      return
    fi
  done

  echo ""
}

INSTALL_DIR=$(find_game_dir)

if [ -z "$INSTALL_DIR" ]; then
  echo -e "\033[31mError: Could not automatically locate Allumeria.exe in Steam folders.\033[0m"
  echo "Please set ALLUMERIA_GAME_PATH to your game directory and run this script again."
  exit 1
fi

echo -e "\033[32mFound Allumeria game directory at: $INSTALL_DIR\033[0m"

# Direct download link to the latest release zip archive
DOWNLOAD_URL="https://api.github.com/repos/$REPO_USER/$REPO_NAME/zipball"

TEMP_ZIP="/tmp/AllumeriaEnhanced_latest.zip"
TEMP_EXTRACT="/tmp/AllumeriaEnhanced_Extract"

echo "Downloading latest release..."
curl -fL -A "$USER_AGENT" -o "$TEMP_ZIP" "$DOWNLOAD_URL"

rm -rf "$TEMP_EXTRACT"
mkdir -p "$TEMP_EXTRACT"

echo "Extracting files..."
unzip -q "$TEMP_ZIP" -d "$TEMP_EXTRACT"

# Handle top-level directory wrapper generated by GitHub release archives
SOURCE_DIR="$TEMP_EXTRACT"
if [ $(ls -1 "$TEMP_EXTRACT" | wc -l) -eq 1 ] && [ -d "$TEMP_EXTRACT"/* ]; then
  SOURCE_DIR="$TEMP_EXTRACT"/*
fi

echo -e "\033[32mInstalling Allumeria Enhanced into game root...\033[0m"

# Skopiowanie zawartości katalogu źródłowego bezpośrednio do katalogu gry (z nadpisaniem istniejących plików)
cp -rf "$SOURCE_DIR"/. "$INSTALL_DIR/"

# Cleanup
rm -f "$TEMP_ZIP"
rm -rf "$TEMP_EXTRACT"

echo -e "\n\033[32mAllumeria Enhanced successfully installed!\033[0m"
